# Generated by Django 4.0 on 2023-08-01 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_student_matric_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotQuestion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='elections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_choice_max', models.PositiveSmallIntegerField(default=1)),
                ('validation_choice_min', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('election_live_url', models.CharField(blank=True, max_length=100, null=True)),
                ('election_live_short_url', models.CharField(blank=True, max_length=100, null=True)),
                ('election_live_preview_url', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('BUILDING', 'BUILDING'), ('LIVE', 'LIVE')], default='BUILDING', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionSetting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='election.election')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionSettingCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='elections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ballot_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='election.ballotquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionSettingParameter',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_type', models.CharField(choices=[('BOOLEAN', 'BOOLEAN'), ('TEXT', 'TEXT')], max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.electionsettingcategory')),
                ('election_setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='election.electionsetting')),
            ],
        ),
        migrations.AddField(
            model_name='ballotquestion',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_questions', to='election.election'),
        ),
    ]
