# Generated by Django 4.0 on 2023-08-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_ballotquestion_unique_elective_post_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='option',
            name='unique_booking',
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('ballot_question', 'title'), name='unique_option'),
        ),
    ]
