# Generated by Django 4.0 on 2023-08-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_remove_option_unique_booking_option_unique_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electionsettingcategory',
            options={'verbose_name_plural': 'Election Setting Categories'},
        ),
        migrations.AlterField(
            model_name='electionsettingcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
