# Generated by Django 4.0 on 2023-08-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_voter_unique_voter_email_and_more'),
        ('election', '0004_alter_electionsettingcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_options', to='voting.Voter'),
        ),
    ]
