# Generated by Django 4.0 on 2023-08-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_option_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionsettingparameter',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
