# Generated by Django 4.0 on 2023-08-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_electionsettingparameter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionsettingparameter',
            name='election_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electionsetting'),
        ),
    ]
