# Generated by Django 4.0 on 2023-08-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_alter_electionsettingparameter_election_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='election_live_preview_url',
        ),
        migrations.RemoveField(
            model_name='election',
            name='election_live_short_url',
        ),
        migrations.RemoveField(
            model_name='election',
            name='election_live_url',
        ),
        migrations.AddField(
            model_name='election',
            name='live_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='election',
            name='preview_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='electionsettingparameter',
            name='election_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_setting_parameters', to='election.electionsetting'),
        ),
    ]
