# Generated by Django 4.0 on 2023-08-13 22:39

import apps.election.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_remove_election_election_live_preview_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='preview_code',
            field=models.CharField(blank=True, default=apps.election.models.generate_url_code, max_length=100, null=True, unique=True),
        ),
    ]
