# Generated by Django 4.0 on 2023-08-03 10:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0004_alter_electionsettingcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pass_name', models.CharField(blank=True, max_length=100)),
                ('pass_key', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election')),
            ],
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=('election', 'email', 'phone_number'), name='unique_voter_email'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=('election', 'phone_number'), name='unique_voter_phone_number'),
        ),
    ]
