# Generated by Django 4.0 on 2023-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voter',
            name='unique_voter_email',
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=('election', 'email'), name='unique_voter_email'),
        ),
    ]
