# Generated by Django 4.0 on 2023-08-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_option_voters'),
        ('voting', '0002_remove_voter_unique_voter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='election.election'),
        ),
    ]
